language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=testing
matrix:
  fast_finish: true
script:
  - "npm run-script test-travis"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database sosicktest;' -U postgres
  - psql -c 'create user sosickstudios;grant all privileges on database sosicktest to sosickstudios;' -U postgres
services:
  - redis-server
