language: node_js
node_js:
  - "0.10"
matrix:
  fast_finish: true
script:
  - "npm run-script test-travis"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database sosick;' -U sosickstudios
